//! Stream cipher for source code encryption.
//!
//! Uses a SHA-256-based keystream generator in counter mode (CTR).
//! The keystream is generated by hashing (key || nonce || counter) repeatedly.
//! This produces a cryptographically strong pseudo-random byte stream that is
//! XORed with the plaintext.
//!
//! Security model: the goal is to make embedded source code unrecoverable by
//! casual inspection (strings, hexdump, decompilers). The key is derived from
//! a passphrase via SHA-256 key stretching (multiple rounds).

use super::sha256::sha256;

/// Number of key-stretching rounds (makes brute-force expensive).
const KDF_ROUNDS: usize = 100_000;

/// Derive a 32-byte key from a passphrase using iterated SHA-256.
/// This is a simplified PBKDF: hash(hash(hash(...passphrase + salt...))).
pub fn derive_key(passphrase: &[u8], salt: &[u8]) -> [u8; 32] {
    let mut material = Vec::with_capacity(passphrase.len() + salt.len());
    material.extend_from_slice(passphrase);
    material.extend_from_slice(salt);

    let mut key = sha256(&material);
    for _ in 0..KDF_ROUNDS {
        let mut next = Vec::with_capacity(64);
        next.extend_from_slice(&key);
        next.extend_from_slice(salt);
        key = sha256(&next);
    }
    key
}

/// Generate a keystream block for a given counter value.
fn keystream_block(key: &[u8; 32], nonce: &[u8; 16], counter: u64) -> [u8; 32] {
    let mut input = Vec::with_capacity(56);
    input.extend_from_slice(key);
    input.extend_from_slice(nonce);
    input.extend_from_slice(&counter.to_be_bytes());
    sha256(&input)
}

/// Encrypt plaintext using the stream cipher. Returns ciphertext.
/// Format of output is just the raw ciphertext (same length as plaintext).
pub fn encrypt(plaintext: &[u8], key: &[u8; 32], nonce: &[u8; 16]) -> Vec<u8> {
    let mut output = Vec::with_capacity(plaintext.len());
    let mut counter: u64 = 0;

    for chunk in plaintext.chunks(32) {
        let ks = keystream_block(key, nonce, counter);
        for (i, &byte) in chunk.iter().enumerate() {
            output.push(byte ^ ks[i]);
        }
        counter += 1;
    }

    output
}

/// Decrypt ciphertext. Since this is a stream cipher (XOR), decryption is
/// identical to encryption.
pub fn decrypt(ciphertext: &[u8], key: &[u8; 32], nonce: &[u8; 16]) -> Vec<u8> {
    encrypt(ciphertext, key, nonce)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_encrypt_decrypt_roundtrip() {
        let key = derive_key(b"my-secret-passphrase", b"salt123");
        let nonce = [42u8; 16];
        let plaintext = b"fn main() { echo \"Hello, World!\" }";

        let ciphertext = encrypt(plaintext, &key, &nonce);
        // Ciphertext must differ from plaintext
        assert_ne!(&ciphertext[..], &plaintext[..]);

        let decrypted = decrypt(&ciphertext, &key, &nonce);
        assert_eq!(&decrypted[..], &plaintext[..]);
    }

    #[test]
    fn test_different_keys_produce_different_ciphertext() {
        let key1 = derive_key(b"key1", b"salt");
        let key2 = derive_key(b"key2", b"salt");
        let nonce = [0u8; 16];
        let plaintext = b"secret data";

        let c1 = encrypt(plaintext, &key1, &nonce);
        let c2 = encrypt(plaintext, &key2, &nonce);
        assert_ne!(c1, c2);
    }

    #[test]
    fn test_no_plaintext_leak() {
        let key = derive_key(b"pass", b"salt");
        let nonce = [7u8; 16];
        let plaintext = b"UNIQUE_MARKER_STRING_12345";
        let ciphertext = encrypt(plaintext, &key, &nonce);

        // The marker must NOT appear in the ciphertext
        let marker = b"UNIQUE_MARKER";
        let found = ciphertext
            .windows(marker.len())
            .any(|w| w == marker);
        assert!(!found, "plaintext marker leaked into ciphertext");
    }
}
